version: '3.12'

name: certificate_refresher
services:
  certificate_refresher:
    build: .
    container_name: certificate_refresher
    volumes:
      # mount ssl folder where the certificates will be stored
      - ${TARGET_SSL_FOLDER}:/usr/src/app/ssl/
    environment:
      # names without extention
      - CERT_NAME=${CERT_NAME}
      - KEY_NAME=${KEY_NAME}
      - CERT_COMMON_NAME=${CERT_COMMON_NAME}
      - CERT_ORGANIZATION=${CERT_ORGANIZATION}
      - CERT_LOCALITY=${CERT_LOCALITY}
      - CERT_STATE=${CERT_STATE}
      - CERT_COUNTRY=${CERT_COUNTRY}
